app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from flask_login import UserMixin

db = SQLAlchemy()

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(45), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String, nullable=False)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password
    
    def saveToDB(self):
        db.session.add(self)
        db.session.commit()

# class Team(db.Model):
#     pass

class Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(45), nullable=False, unique=True)
    ability = db.Column(db.String(45), nullable=False)
    base_xp = db.Column(db.Integer, nullable=False)
    front_shiny = db.Column(db.String(145), nullable=False)
    base_atk = db.Column(db.Integer, nullable=False)
    base_hp = db.Column(db.Integer, nullable=False)
    base_def = db.Column(db.Integer, nullable=False)

    def __init__(self, name, ability, base_xp, front_shiny, base_atk, base_hp, base_def):
        self.name = name
        self.ability = ability
        self.base_xp = base_xp
        self.front_shiny = front_shiny
        self.base_atk = base_atk
        self.base_hp = base_hp
        self.base_def = base_def
        
    def saveToDB(self):
        db.session.add(self)
        db.session.commit()

app/search/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

class searchPoke(FlaskForm):
    searchBody = StringField('Search', validators=[DataRequired(), Length(min=1, max=45)])
    search = SubmitField('Search')

app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class registrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=1, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

class loginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=1, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class editForm(FlaskForm):
    currentPassword = PasswordField('Current Password', validators=[DataRequired()])
    newPassword = PasswordField('New Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('newPassword')])
    submit = SubmitField('Save New Password')

app/__init__.py
from flask import Flask
from config import Config
from .models import db, User
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)

db.init_app(app)
migrate = Migrate(app, db)
login_manager = LoginManager()
login_manager.init_app(app)

login_manager.login_view = "loginUsersPage"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

from app.main.routes import main
from app.search.routes import search
from app.users.routes import users

app.register_blueprint(main)
app.register_blueprint(search)
app.register_blueprint(users)

app/battle/routes.py
from flask import Blueprint

battle = Blueprint('battle', __name__)

app/main/routes.py
from app import app
from flask import render_template, request, redirect, url_for, Blueprint

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def homePage():
    # indexCopy1 = 'This is all placeholder text! Currently learning to pass python data through html via flask + jinja. This will all be beautified later down the road, I promise!'
    return render_template('index.html')

app/search/routes.py
from flask import render_template, request, redirect, url_for, Blueprint
from .forms import searchPoke
from ..models import Pokemon, db
from .services import get_poke_info

search = Blueprint('search', __name__)

@search.route('/pokedex', methods=['GET', 'POST'])
def pokedexPage():
    form = searchPoke()
    if request.method == 'POST':
        if form.validate_on_submit():
            search = form.searchBody.data.lower()
            data = get_poke_info(search)
            name = data['name']
            ability = data['ability']
            base_xp = data['base_xp']
            front_shiny = data['front_shiny']
            base_atk = data['base_atk']
            base_hp = data['base_hp']
            base_def = data['base_def']
            pokemon = Pokemon(name, ability, base_xp, front_shiny, base_atk, base_hp, base_def)
            pokemon.saveToDB()
            return render_template('search.html', name=name, ability=ability, base_xp=base_xp, front_shiny=front_shiny, base_atk=base_atk, base_hp=base_hp, base_def=base_def)
    return render_template('pokedex.html', form = form)

app/users/routes.py
from flask import render_template, request, redirect, url_for, Blueprint, flash
from .forms import registrationForm, loginForm, editForm
from ..models import User, db
from flask_login import login_user, logout_user, current_user, login_required

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def registerUserPage():
    form = registrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            email = form.username.data
            password = form.password.data
            # print(username, email, password)
            #adding user to DB
            user = User(username, email, password)
            user.saveToDB()
            return redirect(url_for('users.loginUserPage'))
    return render_template('register.html', form = form)

@users.route('/login', methods=['GET', 'POST'])
def loginUserPage():
    form = loginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            user = User.query.filter_by(username=username).first()
            if user:
                if user.password == password:
                    login_user(user)
                    flash('You have successfully logged in!')
                    return render_template('index.html')
                else:
                    flash('Wrong Password')
        else:
            print('User does not exist')               
    return render_template('login.html', form = form)

@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profilePage():
    form = editForm()
    user = User.query.filter_by(id = current_user.id).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.currentPassword.data == user.password:
                newPassword = form.confirm_password.data
                user.password = newPassword
                user.saveToDB()
            else:
                flash('Wrong password, please try again')
    return render_template('profile.html', form=form)

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
  <h1 class="container">HOME PAGE</h1>
    <div class="container">
    {{ indexCopy1 }} </div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome Trainers!</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</head>
<nav class="navbar navbar-expand-lg bg-light container">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.homePage') }}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.registerUserPage') }}">Sign Up</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Pokemon GTS
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('search.pokedexPage') }}">Pokedex Search</a></li>
            <li><a class="dropdown-item" href="#">Trainer Battle</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.loginUserPage') }}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.profilePage') }}"></a> {{ current_user.username }}</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<body>
{% block content %}{% endblock %}
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}

  <h1 class="container">Welcome back!</h1>
    <form method="POST" class="container">
        {{ form.hidden_tag() }}
        {{ form.username(class='form-control', placeholder='Username') }}
        {{ form.password(class='form-control', placeholder='Password') }}
        {{ form.submit(class='btn btn-primary') }} <a>Remember Me {{ form.remember }}</a>
    </form>

{% endblock %}

app/templates/pokedex.html
{% extends "layout.html" %}
{% block content %}

  <h1 class="container">Welcome to the Pokedex!</h1>
    <form method="POST" class="container">
      {{ form.hidden_tag() }}
      {{ form.searchBody }}
      {{ form.search }}
    </form>

{% endblock %}

app/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<h1>Your Profile</h1>
<h2>Will be updated soon! For now, you are allowed to change your password below:</h2>
<form method="POST" class="container">
    {{ form.hidden_tag() }}
    {{ form.currentPassword(class='form-control', placeholder='Current Password') }}
    {{ form.newPassword(class='form-control', placeholder='New Password') }}
    {{ form.confirm_password(class='form-control', placeholder='Confirm Password') }}
    {{ form.submit(class='btn btn-primary') }}
</form>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}

  <h1 class="container">Ready to become a Pokemon Master?</h1>
    <form method="POST" class="container">
      {{ form.hidden_tag() }}
      {{ form.username(class='form-control', placeholder='Username') }}
      {{ form.email(class='form-control', placeholder='E-mail Address') }}
      {{ form.password(class='form-control', placeholder='Password') }}
      {{ form.confirm_password(class='form-control', placeholder='Confirm Password') }}
      {{ form.submit(class='btn btn-primary') }}
    </form>

{% endblock %}

app/templates/search.html
{% extends "layout.html" %}
{% block content %}

<h1>Pokedex Results</h1>
<div class="card mb-3" style="max-width: 540px;"> 
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ front_shiny }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{ name.title() }}</h5>
          <p class="card-text">Ability: {{ ability.title() }}</p>
          <p class="card-text">Base XP: {{ base_xp }}</p>
          <p class="card-text">Base HP: {{ base_hp }}</p>
          <p class="card-text">Base ATK: {{ base_atk }}</p>
          <p class="card-text">Base DEF: {{ base_def }}</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}